### PR TITLE
Add Prow config

### PR DESCRIPTION
**Pull request by bobcatfish**

### CODE REVIEW

**Comment by robotcatfish** [comment]
@bobcatfish: cat image

<details>

In response to [this](https://github.com/bobcatfish/catservice/pull/3#issuecomment-522075722):

>/meow


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by bobcatfish** [comment]
YESSSSS

**Comment by robotcatfish** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **bobcatfish**
You can assign the PR to them by writing `/assign @bobcatfish` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=bobcatfish%2Fcatservice).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/bobcatfish/catservice/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by robotcatfish** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/bobcatfish/catservice/pull/3#issuecomment-522076932" title="Approved">bobcatfish</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=bobcatfish%2Fcatservice).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/bobcatfish/catservice/blob/master/OWNERS)~~ [bobcatfish]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by robotcatfish** [comment]
@bobcatfish: cat image

<details>

In response to [this](https://github.com/bobcatfish/catservice/pull/3#issuecomment-522158801):

>/meow


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by robotcatfish** [comment]
@bobcatfish: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
do-the-pipeline | 4b9be49d78a5dd3f0d7bdf946748e501490fa915 | [link]() | `/test do-the-pipeline`

[Full PR test history](https://tekton-releases.appspot.com/pr/bobcatfish_catservice/3). [Your PR dashboard](https://prow.tekton.dev/pr/bobcatfish).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by robotcatfish** [comment]
@bobcatfish: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
do-the-pipeline | 6042a6196a86efb0158e5d7b6dd8ddd31011018e | [link]() | `/test do-the-pipeline`

[Full PR test history](https://tekton-releases.appspot.com/pr/bobcatfish_catservice/3). [Your PR dashboard](https://prow.tekton.dev/pr/bobcatfish).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by robotcatfish** [comment]
@bobcatfish: [dog image](https://random.dog/eebec262-2c4a-4883-9c75-32f9315eb045.jpg)

<details>

In response to [this](https://github.com/bobcatfish/catservice/pull/3#issuecomment-522162639):

>/woof


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by robotcatfish** [comment]
@bobcatfish: [dog image](https://random.dog/d1ed2b85-9753-4756-8fa8-f7c4449719d8.jpg)

<details>

In response to [this](https://github.com/bobcatfish/catservice/pull/3#issuecomment-522162692):

>/woof


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by robotcatfish** [comment]
@bobcatfish: cat image

<details>

In response to [this](https://github.com/bobcatfish/catservice/pull/3#issuecomment-522162734):

>/meow


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by robotcatfish** [comment]
@krzyzacy: cat image

<details>

In response to [this](https://github.com/bobcatfish/catservice/pull/3#issuecomment-522164997):

>/meowvie


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by robotcatfish** [comment]
@bobcatfish: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/bobcatfish/catservice/pull/3#issuecomment-522730293):

>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by bobcatfish** [comment]
> @bobcatfish: you cannot LGTM your own PR.

Well that's gonna be a bit of a problem XD

**Pull request merged**
